spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    initialization-mode: always
    schema: schema.sql
    data: data.sql
  messages:
    basename: i18n/bundle
    encoding: UTF-8

application:
  locale: ru_RU
