spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    initialization-mode: always
    schema: classpath:schema.sql
    data: classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true    

  messages:
    basename: i18n/bundle
    encoding: UTF-8

application:
  locale: ru_RU

server:
  error:
    include-stacktrace: always