INSERT INTO GENRES (NAME) VALUES ('Роман');
INSERT INTO GENRES (NAME) VALUES ('Сказка');
INSERT INTO GENRES (NAME) VALUES ('Комедия');
INSERT INTO GENRES (NAME) VALUES ('Трагедия');
INSERT INTO GENRES (NAME) VALUES ('Пьеса');

INSERT INTO AUTHORS (NAME) VALUES ('Лев Толстой');
INSERT INTO AUTHORS (NAME) VALUES ('Александр Пушкин');
INSERT INTO AUTHORS (NAME) VALUES ('Уильям Шекспир');
INSERT INTO AUTHORS (NAME) VALUES ('Антон Чехов');
INSERT INTO AUTHORS (NAME) VALUES ('Михаил Лермонтов');

INSERT INTO BOOKS (NAME, GENREID) VALUES ('Война и мир', 1);
INSERT INTO BOOKS (NAME, GENREID) VALUES ('Лукоморье', 2);
INSERT INTO BOOKS (NAME, GENREID) VALUES ('Евгений Онегин', 1);
INSERT INTO BOOKS (NAME, GENREID) VALUES ('Много шума из ничего', 3);
INSERT INTO BOOKS (NAME, GENREID) VALUES ('Отелло', 4);
INSERT INTO BOOKS (NAME, GENREID) VALUES ('Вишневый сад', 5);

INSERT INTO BOOKS_AUTHORS (BOOKID, AUTHORID) VALUES (1, 1);
INSERT INTO BOOKS_AUTHORS (BOOKID, AUTHORID) VALUES (2, 2);
INSERT INTO BOOKS_AUTHORS (BOOKID, AUTHORID) VALUES (3, 2);
INSERT INTO BOOKS_AUTHORS (BOOKID, AUTHORID) VALUES (4, 3);
INSERT INTO BOOKS_AUTHORS (BOOKID, AUTHORID) VALUES (5, 3);
INSERT INTO BOOKS_AUTHORS (BOOKID, AUTHORID) VALUES (6, 4);

INSERT INTO COMMENTS (BOOKID, COMMENT) VALUES (1, 'Super book');
INSERT INTO COMMENTS (BOOKID, COMMENT) VALUES (1, 'No, it''s not fine');
