DROP TABLE IF EXISTS COMMENTS;
DROP TABLE IF EXISTS BOOKS_AUTHORS;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;

CREATE TABLE AUTHORS (
    ID BIGSERIAL PRIMARY KEY
  , NAME VARCHAR(255)
);

CREATE TABLE GENRES (
    ID BIGSERIAL PRIMARY KEY
  , NAME VARCHAR(255)
);

CREATE TABLE BOOKS (
    ID BIGSERIAL PRIMARY KEY
  , NAME VARCHAR(255)
  , GENREID BIGINT
  , CONSTRAINT FK_BOOKS_GENRES FOREIGN KEY(GENREID) REFERENCES GENRES(ID)
);

CREATE TABLE BOOKS_AUTHORS (
    BOOKID BIGINT
  , AUTHORID BIGINT
  , CONSTRAINT FK_BOOKS FOREIGN KEY(BOOKID) REFERENCES BOOKS(ID)
  , CONSTRAINT FK_AUTHORS FOREIGN KEY(AUTHORID) REFERENCES AUTHORS(ID) ON DELETE CASCADE
  , PRIMARY KEY (BOOKID, AUTHORID)
);

CREATE TABLE COMMENTS (
    ID BIGSERIAL PRIMARY KEY
  , BOOKID BIGINT
  , COMMENT VARCHAR(4000) NOT NULL
  , CONSTRAINT FK_COMMENTS_BOOKS FOREIGN KEY (BOOKID) REFERENCES BOOKS(ID) ON DELETE CASCADE
);
