CREATE TABLE IF NOT EXISTS AUTHORS (
    ID BIGSERIAL PRIMARY KEY
  , NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS GENRES (
    ID BIGSERIAL PRIMARY KEY
  , NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS BOOKS (
    ID BIGSERIAL PRIMARY KEY
  , NAME VARCHAR(255)
  , GENREID BIGINT
  , CONSTRAINT FK_BOOKS_GENRES FOREIGN KEY(GENREID) REFERENCES GENRES(ID)
);

CREATE TABLE IF NOT EXISTS BOOKS_AUTHORS (
    BOOKID BIGINT
  , AUTHORID BIGINT
  , CONSTRAINT FK_BOOKS FOREIGN KEY(BOOKID) REFERENCES BOOKS(ID)
  , CONSTRAINT FK_AUTHORS FOREIGN KEY(AUTHORID) REFERENCES AUTHORS(ID) ON DELETE CASCADE
  , PRIMARY KEY (BOOKID, AUTHORID)
);

CREATE TABLE IF NOT EXISTS COMMENTS (
    ID BIGSERIAL PRIMARY KEY
  , BOOKID BIGINT
  , COMMENT VARCHAR(4000) NOT NULL
  , CONSTRAINT FK_COMMENTS_BOOKS FOREIGN KEY (BOOKID) REFERENCES BOOKS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS AUTH_ROLE (
    ID BIGSERIAL PRIMARY KEY
  , SYSNAME VARCHAR(255)
  , NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS AUTH_USER (
    ID BIGSERIAL PRIMARY KEY
  , ROLEID BIGINT
  , USERNAME VARCHAR(255)
  , PASSWORD VARCHAR(255)
);


CREATE TABLE IF NOT EXISTS ACL_SID (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  PRINCIPAL TINYINT(1) NOT NULL,
  SID VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY UNIQUE_UK_1 (SID, PRINCIPAL)
);

CREATE TABLE IF NOT EXISTS ACL_CLASS (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  CLASS VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY UNIQUE_UK_2 (CLASS)
);
 
CREATE TABLE IF NOT EXISTS ACL_ENTRY (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  ACL_OBJECT_IDENTITY BIGINT(20) NOT NULL,
  ACE_ORDER INT(11) NOT NULL,
  SID BIGINT(20) NOT NULL,
  MASK INT(11) NOT NULL,
  GRANTING TINYINT(1) NOT NULL,
  AUDIT_SUCCESS TINYINT(1) NOT NULL,
  AUDIT_FAILURE TINYINT(1) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY UNIQUE_UK_4 (ACL_OBJECT_IDENTITY,ACE_ORDER)
);
 
CREATE TABLE IF NOT EXISTS ACL_OBJECT_IDENTITY (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  OBJECT_ID_CLASS BIGINT(20) NOT NULL,
  OBJECT_ID_IDENTITY BIGINT(20) NOT NULL,
  PARENT_OBJECT BIGINT(20) DEFAULT NULL,
  OWNER_SID BIGINT(20) DEFAULT NULL,
  ENTRIES_INHERITING TINYINT(1) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY UNIQUE_UK_3 (OBJECT_ID_CLASS,OBJECT_ID_IDENTITY)
);

ALTER TABLE ACL_ENTRY
ADD FOREIGN KEY (ACL_OBJECT_IDENTITY) REFERENCES ACL_OBJECT_IDENTITY(ID);

ALTER TABLE ACL_ENTRY
ADD FOREIGN KEY (SID) REFERENCES ACL_SID(ID);

ALTER TABLE ACL_OBJECT_IDENTITY
ADD FOREIGN KEY (PARENT_OBJECT) REFERENCES ACL_OBJECT_IDENTITY (ID);

ALTER TABLE ACL_OBJECT_IDENTITY
ADD FOREIGN KEY (OBJECT_ID_CLASS) REFERENCES ACL_CLASS (ID);

ALTER TABLE ACL_OBJECT_IDENTITY
ADD FOREIGN KEY (OWNER_SID) REFERENCES ACL_SID (ID);

