DROP TABLE IF EXISTS AUTHORS;

CREATE TABLE AUTHORS (
    ID BIGSERIAL PRIMARY KEY
  , NAME VARCHAR(255)
);

DROP TABLE IF EXISTS GENRES;

CREATE TABLE GENRES (
    ID BIGSERIAL PRIMARY KEY
  , NAME VARCHAR(255)
);

DROP TABLE IF EXISTS BOOKS;

CREATE TABLE BOOKS (
    ID BIGSERIAL PRIMARY KEY
  , NAME VARCHAR(255)
  , GENREID BIGINT
  , CONSTRAINT FK_BOOKS_GENRES FOREIGN KEY(GENREID) REFERENCES GENRES(ID)
);

DROP TABLE IF EXISTS BOOKS_AUTHORS;

CREATE TABLE BOOKS_AUTHORS (
    BOOKID BIGINT
  , AUTHORID BIGINT
  , CONSTRAINT FK_BOOKS FOREIGN KEY(BOOKID) REFERENCES BOOKS(ID)
  , CONSTRAINT FK_AUTHORS FOREIGN KEY(AUTHORID) REFERENCES AUTHORS(ID)
  , PRIMARY KEY (BOOKID, AUTHORID)
);

DROP TABLE IF EXISTS COMMENTS;

CREATE TABLE COMMENTS (
    ID BIGSERIAL PRIMARY KEY
  , BOOKID BIGINT
  , COMMENT VARCHAR(4000) NOT NULL
  , CONSTRAINT FK_COMMENTS_BOOKS FOREIGN KEY (BOOKID) REFERENCES BOOKS(ID)
);
