INSERT INTO AUTHORS (NAME) VALUES ('Author 1');
INSERT INTO AUTHORS (NAME) VALUES ('Author 2');
INSERT INTO AUTHORS (NAME) VALUES ('Author 3');
INSERT INTO AUTHORS (NAME) VALUES ('Author 4');

INSERT INTO GENRES (NAME) VALUES ('Genre 1');
INSERT INTO GENRES (NAME) VALUES ('Genre 2');
INSERT INTO GENRES (NAME) VALUES ('Genre 3');
INSERT INTO GENRES (NAME) VALUES ('Genre 4');

INSERT INTO BOOKS (NAME, AUTHORID, GENREID) VALUES ('Book 1', 1, 1);
INSERT INTO BOOKS (NAME, AUTHORID, GENREID) VALUES ('Book 2', 2, 1);
INSERT INTO BOOKS (NAME, AUTHORID, GENREID) VALUES ('Book 3', 2, 2);
INSERT INTO BOOKS (NAME, AUTHORID, GENREID) VALUES ('Book 4', 3, 1);
INSERT INTO BOOKS (NAME, AUTHORID, GENREID) VALUES ('Book 5', 3, 3);

INSERT INTO COMMENTS (BOOKID, COMMENT) VALUES (1, 'Comment 1-1');
INSERT INTO COMMENTS (BOOKID, COMMENT) VALUES (1, 'Comment 1-2');
