INSERT INTO AUTHORS (NAME) VALUES ('Author 1');
INSERT INTO AUTHORS (NAME) VALUES ('Author 2');
INSERT INTO AUTHORS (NAME) VALUES ('Author 3');
INSERT INTO AUTHORS (NAME) VALUES ('Author 4');

INSERT INTO GENRES (NAME) VALUES ('Genre 1');
INSERT INTO GENRES (NAME) VALUES ('Genre 2');
INSERT INTO GENRES (NAME) VALUES ('Genre 3');
INSERT INTO GENRES (NAME) VALUES ('Genre 4');

INSERT INTO BOOKS (NAME, GENREID) VALUES ('Book 1', 1);
INSERT INTO BOOKS (NAME, GENREID) VALUES ('Book 2', 1);
INSERT INTO BOOKS (NAME, GENREID) VALUES ('Book 3', 2);
INSERT INTO BOOKS (NAME, GENREID) VALUES ('Book 4', 1);
INSERT INTO BOOKS (NAME, GENREID) VALUES ('Book 5', 3);

INSERT INTO BOOKS_AUTHORS (BOOKID, AUTHORID) VALUES (1, 1);
INSERT INTO BOOKS_AUTHORS (BOOKID, AUTHORID) VALUES (2, 2);
INSERT INTO BOOKS_AUTHORS (BOOKID, AUTHORID) VALUES (3, 2);
INSERT INTO BOOKS_AUTHORS (BOOKID, AUTHORID) VALUES (4, 3);
INSERT INTO BOOKS_AUTHORS (BOOKID, AUTHORID) VALUES (5, 3);

INSERT INTO COMMENTS (BOOKID, COMMENT) VALUES (1, 'Comment 1-1');
INSERT INTO COMMENTS (BOOKID, COMMENT) VALUES (1, 'Comment 1-2');

INSERT INTO AUTH_ROLE (ID, SYSNAME, NAME) VALUES (1, 'ADMIN', 'Administrator');
INSERT INTO AUTH_ROLE (ID, SYSNAME, NAME) VALUES (2, 'USER', 'Simple User');

INSERT INTO AUTH_USER (ID, ROLEID, USERNAME, PASSWORD) VALUES (1, 1, 'admin', '$2a$10$8R/UxQ/K/IgX0jeTQQnaqeoes18cRFwa6z4FsKr4daLsav/roPsmm');
INSERT INTO AUTH_USER (ID, ROLEID, USERNAME, PASSWORD) VALUES (2, 2, 'user', '$2a$10$8R/UxQ/K/IgX0jeTQQnaqeoes18cRFwa6z4FsKr4daLsav/roPsmm');
